/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kamac8665
 */
public class FormMakingAPizza extends javax.swing.JFrame {

    /**
     * Creates new form FormMakingAPizza
     */
    public FormMakingAPizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backgroundPanel = new javax.swing.JPanel();
        pictureLabel1 = new javax.swing.JLabel();
        pictureLabel2 = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();
        pizzaDiameterLabel = new javax.swing.JLabel();
        pizzaDiameterInput = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        subtotalLabel = new javax.swing.JLabel();
        taxesLabel = new javax.swing.JLabel();
        grandtotalLabel = new javax.swing.JLabel();
        subtotalOutput = new javax.swing.JLabel();
        taxesOutput = new javax.swing.JLabel();
        outputMessageLabel = new javax.swing.JLabel();
        grandtotalOutput = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundPanel.setBackground(new java.awt.Color(153, 204, 255));

        pictureLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/201102-r-sweet-potato-pizza.jpg"))); // NOI18N

        pictureLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/19722_1403366336_0.jpg"))); // NOI18N

        titleLabel1.setFont(new java.awt.Font("Script MT Bold", 2, 36)); // NOI18N
        titleLabel1.setText("Putrid's");

        titleLabel2.setFont(new java.awt.Font("Script MT Bold", 2, 36)); // NOI18N
        titleLabel2.setText("Pizzeria");

        pizzaDiameterLabel.setFont(new java.awt.Font("Segoe Media Center Light", 2, 16)); // NOI18N
        pizzaDiameterLabel.setText("Diameter of Pizza (cm):");

        pizzaDiameterInput.setFont(new java.awt.Font("Segoe Media Center Light", 0, 16)); // NOI18N
        pizzaDiameterInput.setText("   0  ");

        enterButton.setBackground(new java.awt.Color(0, 51, 255));
        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        subtotalLabel.setFont(new java.awt.Font("Segoe Media Center Light", 2, 16)); // NOI18N
        subtotalLabel.setText("Subtotal:");

        taxesLabel.setFont(new java.awt.Font("Segoe Media Center Light", 2, 16)); // NOI18N
        taxesLabel.setText("Taxes:");

        grandtotalLabel.setFont(new java.awt.Font("Segoe Media Center Light", 2, 16)); // NOI18N
        grandtotalLabel.setText("Grandtotal:");

        subtotalOutput.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        subtotalOutput.setText("$0.00");

        taxesOutput.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        taxesOutput.setText("$0.00");

        outputMessageLabel.setFont(new java.awt.Font("Segoe Media Center Light", 2, 16)); // NOI18N
        outputMessageLabel.setText("Grandtotal:");

        grandtotalOutput.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        grandtotalOutput.setText("$0.00");

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pictureLabel1)
                        .addComponent(pictureLabel2)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel1)))
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(pizzaDiameterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(enterButton)
                            .addComponent(pizzaDiameterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                                .addComponent(outputMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(27, 27, 27))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(subtotalLabel)
                                    .addComponent(taxesLabel)
                                    .addComponent(grandtotalLabel))
                                .addGap(39, 39, 39)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(grandtotalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                        .addComponent(subtotalOutput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(taxesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 97, Short.MAX_VALUE))))))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pictureLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pizzaDiameterLabel)
                            .addComponent(pizzaDiameterInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(enterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(outputMessageLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalLabel)
                            .addComponent(subtotalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxesLabel)
                            .addComponent(taxesOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandtotalLabel)
                            .addComponent(grandtotalOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pictureLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        
//costs per pizza
        double labour = 0.75;
        double rent = 0.99;
        double ingredients = 0.50;
        
//get pizza size
        double diameter;
        diameter = Double.parseDouble(pizzaDiameterInput.getText());
//total cost variable        
        double cost;
//labour costs and rent costs added together        
        double lr;
        lr = labour+rent;
//cost of pizza per diameter        
        double dcost;
        dcost = diameter*0.50;
//total cost
        double totalcost;
        totalcost = dcost+lr;
//variables
        double subtotal;
        double taxes;
        double grandtotal;
        
//if else statements        
        
        if(diameter <= 15){
            outputMessageLabel.setText("We are going to make you a cute little pizza!");
            subtotal = totalcost;
            subtotal = subtotal*100;
            subtotal = Math.round(subtotal);
            subtotal = subtotal/100;
            subtotalOutput.setText("$"+subtotal);
            
            taxes = totalcost*0.13;
            taxes = taxes*100;
            taxes = Math.round(taxes);
            taxes = taxes/100;
            taxesOutput.setText("$"+taxes);
            
            grandtotal = subtotal+taxes;
            grandtotal = grandtotal*100;
            grandtotal = Math.round(grandtotal);
            grandtotal = grandtotal/100;
            grandtotalOutput.setText("$"+grandtotal);
        }
        else if(diameter <=40){
            outputMessageLabel.setText("This will be delicious!");
            subtotal = totalcost;
            subtotal = subtotal*100;
            subtotal = Math.round(subtotal);
            subtotal = subtotal/100;
            subtotalOutput.setText("$"+subtotal);
            
            taxes = totalcost*0.13;
            taxes = taxes*100;
            taxes = Math.round(taxes);
            taxes = taxes/100;
            taxesOutput.setText("$"+taxes);
            
            grandtotal = subtotal+taxes;
            grandtotal = grandtotal*100;
            grandtotal = Math.round(grandtotal);
            grandtotal = grandtotal/100;
            grandtotalOutput.setText("$"+grandtotal);
        }
        else if(diameter >=41){
            outputMessageLabel.setText("Whoa,big pizza!");
            subtotal = totalcost;
            subtotal = subtotal*100;
            subtotal = Math.round(subtotal);
            subtotal = subtotal/100;
            subtotalOutput.setText("$"+subtotal);
            
            taxes = totalcost*0.13;
            taxes = taxes*100;
            taxes = Math.round(taxes);
            taxes = taxes/100;
            taxesOutput.setText("$"+taxes);
            
            grandtotal = subtotal+taxes;
            grandtotal = grandtotal*100;
            grandtotal = Math.round(grandtotal);
            grandtotal = grandtotal/100;
            grandtotalOutput.setText("$"+grandtotal);
        }








    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMakingAPizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMakingAPizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton enterButton;
    private javax.swing.JLabel grandtotalLabel;
    private javax.swing.JLabel grandtotalOutput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel outputMessageLabel;
    private javax.swing.JLabel pictureLabel1;
    private javax.swing.JLabel pictureLabel2;
    private javax.swing.JTextField pizzaDiameterInput;
    private javax.swing.JLabel pizzaDiameterLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel subtotalOutput;
    private javax.swing.JLabel taxesLabel;
    private javax.swing.JLabel taxesOutput;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    // End of variables declaration//GEN-END:variables
}
